language: python


python:
  - 3.9

services:
  postgresql
addons:
  postgresql: '9.5'

env:
  PIPENV_VENV_IN_PROJECT=1
  PIPENV_IGNORE_VIRUTALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
script:
  - pipenv run flake8