language: python


python:
  - 3.9

env:
  PIPENV_VENV_IN_PROJECT=1
  PIPENV_IGNORE_VIRUTALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev
  - cp contrib/env-sample .env
script:
  - pipenv run flake8